language: cpp

# Generating core dumps requires a sudo machine
# https://github.com/travis-ci/travis-ci/issues/3754
sudo: true

addons:
 apt:
  packages:
  - gdb

env:
  matrix:
   - CRASH_PLEASE=boooooooom
   - HAPPY_NO_CRASH=all-good

compiler:
 # gcc compiler, clang would be fine too
 - gcc

install:
 # What is the current file size max for core files?
 # It is usually 0, which means no core file will be dumped if there is a crash 
 - ulimit -c

before_script:
 # Set the core file limit to unlimited so a core file is generated upon crash
 - ulimit -c unlimited -S

script:
 # Compile our demo program which will crash if
 # the CRASH_PLEASE environment variable is set (to anything)
 - make
 # Run the program to prompt a crash
 - ./test

after_failure:
 # If the program returned an error code, now we check for a
 # core file in the current working directory and dump the backtrace out
 - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
